spring.application.name=IMS-Backend

# Database Configuration (PostgreSQL for Railway)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/imsdb}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

# JWT Security Configuration
jwt.secret=Qok7QmQ56WMVcfGsu4zdK91Huvjx7M1OajxtMSRDEBY=
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Time zone configuration
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jackson.time-zone=Asia/Kolkata